# Generated by Django 2.1.5 on 2019-02-06 18:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0002_color_size'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('image', models.ImageField(default=None, upload_to='uploads/products/')),
                ('price', models.FloatField()),
                ('offer_price', models.FloatField(blank=True, null=True)),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(default=None, null=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product', to='webapp.Category')),
                ('color', models.ManyToManyField(to='webapp.Color')),
                ('size', models.ManyToManyField(to='webapp.Size')),
            ],
            options={
                'verbose_name_plural': 'Products',
            },
        ),
    ]
