# Generated by Django 2.1.5 on 2019-02-07 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0005_sku'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favourite',
            name='updated_at',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
